import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Footer from '@/components/Footer';
import Header from '@/components/Header';

import ThemeSwitch from '@/components/theme-switch'
import ThemeContextProvider from '@/context/theme-context'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'otte.net - Andreas Otte Astrofotografie',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 text-gray-950 relative 
      dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90`}>
        <div className='page min-h-screen relative'>
        <ThemeContextProvider>
          <Header/>
          <div>{children}</div>
          <Footer />
          <ThemeSwitch />
        </ThemeContextProvider>
        </div>
      </body>
    </html>
  )
}
